project:
  type: book

book:
  repo-url: https://github.com/smart-stats/ds4bio_book
  title: "Data science and AI for the bio/medical sciences using python"
  author: "Brian Caffo"
  date: "2/24/2023"
  
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - intro_markdown.qmd
        - intro_unix.qmd
        - intro_git.qmd
        - intro_html.qmd
    - part: python.qmd
      chapters:
        - python_basic.qmd
        - python_programming.qmd
        - python_functions.qmd
        - python_virtual_environments.qmd
        - python_practice.qmd
    - part: data.qmd
      chapters:
        - data_cleaning_example.qmd
        - data_sqlite.qmd
        - data_advanced_databases.qmd
        - data_webscraping.qmd
        - data_advanced_webscraping.qmd
    - part: graphics.qmd
      chapters:
        - graphics_eda.qmd
        - graphics_interactive.qmd
        - graphics_advanced_interactive.qmd
        - graphics_theory.qmd
        - graphics_images.qmd
    - statistics.qmd
    - supervised.qmd
    - unsupervised.qmd
    - part: nns.qmd
      chapters:
        - nns_intro.qmd
        - nns_basic_regression.qmd
        - nns_logistic_regression.qmd
        - nns_pytorch_example.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



